name: 'AKS initial basic element on Azure Portal'
on:
  push:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-init-env*'
  pull_request:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-init-env*'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        echo "Result Environment Prepare:" > ./result-env
        az group create --name ${{ secrets.AZURE_RESOURCEGROUP }} --location ${{ secrets.AZURE_REGION }} >> ./result-env
        az storage account create --name ${{ secrets.AZURE_STORAGEACCOUNT }} --resource-group ${{ secrets.AZURE_RESOURCEGROUP}} --location ${{ secrets.AZURE_REGION }} --sku Standard_RAGRS --kind StorageV2 >> ./result-env
        az storage container create --name tfstate --account-name ${{ secrets.AZURE_STORAGEACCOUNT }}  --fail-on-exist >> ./result-env
    - uses: azure/login@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear