name: 'AKS destroy basic element on Azure Portal'
 
on:
  push:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-destroy-env*'
  pull_request:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-destroy-env*'

jobs:
  destroy-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        echo "Result to Destroy Environment:" > ./result-env
        az storage container delete --name tfstate --account-name ${{ secrets.AZURE_STORAGEACCOUNT }} >> ./result-env
        az storage account delete --name ${{ secrets.AZURE_STORAGEACCOUNT }} >> ./result-env
        az group delete --name ${{ secrets.AZURE_RESOURCEGROUP }} --yes -y >> ./result-env
        
    - uses: azure/login@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear