name: 'AKS modified cluster'
on:
  push:
    tags:
      - 'aks-cluster-modify*'
  pull_request:
    tags:
      - 'aks-cluster-modify*'

jobs:
  modify-cluster:
    runs-on: ubuntu-latest
    env:
        working-directory: ./azure-aks/
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      # Checkout code
    - uses: actions/checkout@master
      name: Git checkout code

    - name: AKS readiness verify
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: AKS initialize
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: init
      run: terraform init -input=false

    - name: AKS validation configuration step1
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: validate
      run: terraform validate -no-color

    - name: AKS validation configuration step2
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: plan
      run: terraform plan -no-color -out=tfplan -input=false
      continue-on-error: true

    - name: AKS create cluster
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: plan
      run: terraform apply -input=false tfplan
      continue-on-error: true

    - name: AKS export output
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
      id: output
      run: terraform output kube_config > aks-config
      continue-on-error: true

    - name: Export configuration (KUBECONFIG)
      run: | 
        # Extrace kubeconfig from state file
        tail -n +2 "aks-config" > "aks-config.tmp" && mv "aks-config.tmp" "aks-config"
        sed '$d' aks-config > "aks-config.tmp" && mv "aks-config.tmp" "aks-config" && rm "aks-config.tmp"

    - uses: actions-js/push@master
      name: Commit and push result back
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Commit for update result create environment"