name: 'AKS initial basic element on Azure Portal'
on:
  push:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-init-env*'
  pull_request:
    branches:
      - main
      - 'customer/**'
      - 'dev/**'
    tags:
      - 'aks-init-env*'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@master
      name: Git checkout code

      # Log into Azure
    - uses: azure/login@v1
      name: Azure login to portal
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Run Azure CLI
    - uses: azure/CLI@v1
      name: Run script az cli for create elements
      with:
        azcliversion: 2.34.1
        inlineScript: |
          #!/bin/bash
            if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ secrets.AZURE_RESOURCEGROUP }} --location ${{ secrets.AZURE_REGION }}
              echo "Azure resource group created"
            fi

            az storage account create --name ${{ secrets.AZURE_STORAGEACCOUNT }} --resource-group ${{ secrets.AZURE_RESOURCEGROUP}} --location ${{ secrets.AZURE_REGION }} --sku Standard_RAGRS --kind StorageV2
            az storage container create --name tfstate --account-name ${{ secrets.AZURE_STORAGEACCOUNT }}  --fail-on-exist
        
    - uses: azure/login@v1
      name: Azure logout from protal
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear

    - uses: actions-js/push@master
      name: Commit and push result back
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Commit for update result create environment"